version: '3.9'

services:
    db:
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: app
            MYSQL_USER: app
            MYSQL_PASSWORD: admin
        image: mariadb:10.9
        ports:
            - "8021:3306"
        volumes:
            - database:/var/lib/mysql

    nginx:
        build: ./.docker/nginx
        links:
            - php
        ports:
            - "8020:80"
        user: "app"
        volumes:
            - ./:/var/www/project

    php:
        build: ./.docker/php
        environment:
            PHP_INI_SCAN_DIR: "/usr/local/etc/php/conf.d:/usr/local/etc/php/custom.d"
        user: "app"
        volumes:
            - ./:/var/www/project
            - ./.docker/php/ini:/usr/local/etc/php/custom.d

volumes:
    database:
        name: "lf10"
